//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_LinkRight_H
#define METASPRITE_LinkRight_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define LinkRight_TILE_ORIGIN 0
#define LinkRight_TILE_W 8
#define LinkRight_TILE_H 16
#define LinkRight_WIDTH 16
#define LinkRight_HEIGHT 16
#define LinkRight_TILE_COUNT 8
#define LinkRight_PALETTE_COUNT 1
#define LinkRight_COLORS_PER_PALETTE 4
#define LinkRight_TOTAL_COLORS 4
#define LinkRight_PIVOT_X 8
#define LinkRight_PIVOT_Y 8
#define LinkRight_PIVOT_W 16
#define LinkRight_PIVOT_H 16

BANKREF_EXTERN(LinkRight)

extern const palette_color_t LinkRight_palettes[4];
extern const uint8_t LinkRight_tiles[128];

extern const metasprite_t* const LinkRight_metasprites[2];

#endif
