//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_LinkUp_H
#define METASPRITE_LinkUp_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define LinkUp_TILE_ORIGIN 0
#define LinkUp_TILE_W 8
#define LinkUp_TILE_H 16
#define LinkUp_WIDTH 16
#define LinkUp_HEIGHT 16
#define LinkUp_TILE_COUNT 8
#define LinkUp_PALETTE_COUNT 1
#define LinkUp_COLORS_PER_PALETTE 4
#define LinkUp_TOTAL_COLORS 4
#define LinkUp_PIVOT_X 8
#define LinkUp_PIVOT_Y 8
#define LinkUp_PIVOT_W 16
#define LinkUp_PIVOT_H 16

BANKREF_EXTERN(LinkUp)

extern const palette_color_t LinkUp_palettes[4];
extern const uint8_t LinkUp_tiles[128];

extern const metasprite_t* const LinkUp_metasprites[2];

#endif
