//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_LinkDown_H
#define METASPRITE_LinkDown_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define LinkDown_TILE_ORIGIN 0
#define LinkDown_TILE_W 8
#define LinkDown_TILE_H 16
#define LinkDown_WIDTH 16
#define LinkDown_HEIGHT 16
#define LinkDown_TILE_COUNT 8
#define LinkDown_PALETTE_COUNT 1
#define LinkDown_COLORS_PER_PALETTE 4
#define LinkDown_TOTAL_COLORS 4
#define LinkDown_PIVOT_X 8
#define LinkDown_PIVOT_Y 8
#define LinkDown_PIVOT_W 16
#define LinkDown_PIVOT_H 16

BANKREF_EXTERN(LinkDown)

extern const palette_color_t LinkDown_palettes[4];
extern const uint8_t LinkDown_tiles[128];

extern const metasprite_t* const LinkDown_metasprites[2];

#endif
