//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Moblin_H
#define METASPRITE_Moblin_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Moblin_TILE_ORIGIN 0
#define Moblin_TILE_W 8
#define Moblin_TILE_H 16
#define Moblin_WIDTH 16
#define Moblin_HEIGHT 16
#define Moblin_TILE_COUNT 16
#define Moblin_PALETTE_COUNT 2
#define Moblin_COLORS_PER_PALETTE 4
#define Moblin_TOTAL_COLORS 8
#define Moblin_PIVOT_X 8
#define Moblin_PIVOT_Y 8
#define Moblin_PIVOT_W 16
#define Moblin_PIVOT_H 16

BANKREF_EXTERN(Moblin)

extern const palette_color_t Moblin_palettes[8];
extern const uint8_t Moblin_tiles[256];

extern const metasprite_t* const Moblin_metasprites[8];

#endif
