//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(palettes)

const palette_color_t palettes_palettes[8] = {
	RGB8(  0, 57,115), RGB8(  0,  0,  0), RGB8( 16,173, 66), RGB8(255,189,140)
	,
	RGB8(  0, 57,115), RGB8(  0,  0,  0), RGB8(255,189,140), RGB8( 25,132,255)
	
};

const uint8_t palettes_tiles[32] = {
	0xff,0xff,0xff,0xff,
	0xff,0xff,0xff,0xff,
	0xff,0xff,0xff,0xff,
	0xff,0xff,0xff,0xff,
	0xff,0xff,0xff,0xff,
	0xff,0xff,0xff,0xff,
	0xff,0xff,0xff,0xff,
	0xff,0xff,0xff,0xff
	
};

const metasprite_t palettes_metasprite0[] = {
	METASPR_ITEM(-8, -8, 0, 0), METASPR_ITEM(0, 8, 0, 0), METASPR_TERM
};

const metasprite_t palettes_metasprite1[] = {
	METASPR_ITEM(-8, -8, 0, 0), METASPR_ITEM(0, 8, 0, 0), METASPR_TERM
};

const metasprite_t* const palettes_metasprites[2] = {
	palettes_metasprite0, palettes_metasprite1
};
